apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: jdbc:postgresql://database-fs-restaurant.cdnkrvkiwrsm.eu-west-2.rds.amazonaws.com/DB_FS_RESTAURANT
  foodcataloguedb_url: jdbc:postgresql://database-fs-restaurant.cdnkrvkiwrsm.eu-west-2.rds.amazonaws.com:5432/DB_FS_FOODCATALOGUE
  userdb_url: jdbc:postgresql://database-fs-restaurant.cdnkrvkiwrsm.eu-west-2.rds.amazonaws.com:5432/DB_FS_USERDETAILS
  orderdb_url: mongodb+srv://postgres:postgres@atlas-fs-cluster.jzw9p5e.mongodb.net/?retryWrites=true&w=majority
  eureka_service_address: http://eureka-0.eureka-service:8761/eureka

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  