apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: chrislain/fs-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djdk.tls.client.protocols=TLSv1.2"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: orderdb_url
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "orderdb"

---
apiVersion: v1
kind: Service
metadata:
  name: oder-service
spec:
  selector:
    app: orderapp
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092